### PR TITLE
Add luv.poweroff kernel command line option to call poweroff at the end of the tests

### PR DESCRIPTION
**Pull request by mattface**

### CODE REVIEW

**Comment by ricardon** [comment]
Thanks! This looks good to me. Would you mind documenting this in meta-luv/README? We have a bunch of undocumented options. This looks like a great opportunity to start documenting them. Maybe you can start a section VI. LUV options.

**Comment by mattface** [comment]
I've noticed that luv.halt actually calls halt with -p to ask for power off, so I suggest making luv.halt just halt, and luv.poweroff power off the machine.

**Comment by ricardon** [comment]
Thanks for doing this. I will go ahead and merge this. It will show up first in the next and jethro-next branches.

**Comment by ricardon** [comment]
Applied after minor rewording of commit message. I also added your Signed-off-by line.

**Pull request closed without merging**
